apps/core/urls.py
from django.conf.urls import url

from .views import (
    TicketDetailView,
    TicketCreateView,
    TicketListView,
    TicketUpdateView,
    ChangeStatusView
)


urlpatterns = [
    url(r'^view/(?P<pk>\d+)/$', TicketDetailView.as_view(), name="view"),
    url(r'^add/$', TicketCreateView.as_view(), name="add"),
    url(r'^list/$', TicketListView.as_view(), name="list"),
    url(r'^update/(?P<pk>\d+)/$', TicketUpdateView.as_view(), name="update"),
    url(r'^status/update/(?P<pk>\d+)/', ChangeStatusView.as_view(), name="status_update"),
]

slacalculator/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

from core.views import HomePageView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/', views.login, name='auth_login'),
    url(r'^accounts/logout/', views.logout, name='auth_logout'),
    url(r'^tickets/', include('core.urls', namespace='tickets')),
    url(r'^$', HomePageView.as_view(), name="index"),
]

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <title>SLA Calculator :: {% block title %}{% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="description" content="Gerenciador de SLA de tickets"/>
    <meta name="keywords" content="SLA, Gov, Python, Django, calculator"/>
    <meta name="author" content="Bruno Barbosa">
    <meta name="generator" content="Django">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/ui-lightness/jquery-ui-1.10.0.custom.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/base-admin-3.css' %}" rel="stylesheet">
    <link href="{% static 'css/base-admin-3-responsive.css' %}" rel="stylesheet">

    <link href="{% static 'css/pages/dashboard.css' %}" rel="stylesheet">

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block stylesheets %}

    {% endblock %}

  </head>

<body>

<nav class="navbar navbar-inverse" role="navigation">

    <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="icon-cog"></i>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">SLA Calculator</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">

            <a href="javascript:" class="dropdown-toggle" data-toggle="dropdown">
                <i class="icon-user"></i>
                {{ user }}
                <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            </ul>

        </li>
    </ul>

    <form class="navbar-form navbar-right" role="search">
      <div class="form-group">
        <input type="text" class="form-control input-sm search-query" placeholder="Search">
      </div>
    </form>
  </div><!-- /.navbar-collapse -->
</div> <!-- /.container -->
</nav>


<div class="subnavbar">

	<div class="subnavbar-inner">

		<div class="container">

			<a href="javascript:;" class="subnav-toggle" data-toggle="collapse" data-target=".subnav-collapse">
              <span class="sr-only">Toggle navigation</span>
              <i class="icon-reorder"></i>

            </a>

			<div class="collapse subnav-collapse">
				<ul class="mainnav">

					<li class="active">
						<a href="{% url 'index' %}">
							<i class="icon-home"></i>
							<span>Home</span>
						</a>
					</li>

					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-th"></i>
							<span>Tickets</span>
							<b class="caret"></b>
						</a>

						<ul class="dropdown-menu">
							<li><a href="{% url 'tickets:add' %}">Novo</a></li>
                            <li><a href="{% url 'tickets:list' %}">Listar todos</a></li>
                            <li><a href="#">Sustentação</a></li>
                            <li><a href="#">Desenvolvimento</a></li>
							<li><a href="#">Projetos</a></li>
						</ul>
					</li>

					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon-bar-chart"></i>
							<span>SLA</span>
						</a>
					</li>

				</ul>
			</div> <!-- /.subnav-collapse -->

		</div> <!-- /container -->

	</div> <!-- /subnavbar-inner -->

</div> <!-- /subnavbar -->


<div class="main">

    <div class="container">

        <div class="row">
            <div class="col-md-12 col-xs-12">
                <ol class="breadcrumb">
                    <li><a href="{% url 'index' %}">Home</a></li>
                    {% block breadcrumbs %}
                    <li class="active">Painel</li>
                    {% endblock %}
                </ol>
            </div>
        </div>

		{% block content %}

		{% endblock %}

    </div> <!-- /container -->

</div> <!-- /main -->


<div class="footer">

	<div class="container">

		<div class="row">

			<div id="footer-copyright" class="col-md-6 col-xs-6">
				&copy; 2015 Bruno Barbosa.
			</div> <!-- /span6 -->

			<div id="footer-terms" class="col-md-6 col-xs-6">
				<a href="http://www.djangoproject.com/" target="_blank">
					<img src="https://www.djangoproject.com/m/img/badges/djangosite80x15.gif"
					     border="0" alt="A Django site." title="A Django site." />
				</a>
			</div> <!-- /.span6 -->

		</div> <!-- /row -->

	</div> <!-- /container -->

</div> <!-- /footer -->





<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/libs/jquery-1.9.1.min.js' %}"></script>
<script src="{% static 'js/libs/jquery-ui-1.10.0.custom.min.js' %}"></script>
<script src="{% static 'js/plugins/datepicker/datepicker-pt-BR.js' %}"></script>
<script src="{% static 'js/plugins/mask/jquery.mask.js' %}"></script>
<script src="{% static 'js/libs/bootstrap.min.js' %}"></script>

<script src="{% static 'js/plugins/flot/jquery.flot.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.pie.js' %}"></script>
<script src="{% static 'js/plugins/flot/jquery.flot.resize.js' %}"></script>

<script src="{% static 'js/Application.js' %}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $.datepicker.setDefaults( $.datepicker.regional[ "pt-BR" ] );
    });
</script>

{% block js %}

{% endblock %}

  </body>
</html>