apps/core/urls.py
from django.conf.urls import url

from .views import (
    TicketDetailView,
    TicketCreateView,
    TicketListView,
    TicketUpdateView,
    ChangeStatusView
)


urlpatterns = [
    url(r'^view/(?P<pk>\d+)/$', TicketDetailView.as_view(), name="view"),
    url(r'^add/$', TicketCreateView.as_view(), name="add"),
    url(r'^list/$', TicketListView.as_view(), name="list"),
    url(r'^update/(?P<pk>\d+)/$', TicketUpdateView.as_view(), name="update"),
    url(r'^status/update/(?P<pk>\d+)/', ChangeStatusView.as_view(), name="status_update"),
]

apps/core/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from utils.choice import Choice
from workdays import workday, networkdays
from django_fsm import FSMField, transition


@python_2_unicode_compatible
class Queue(models.Model):

    title = models.CharField(_("Título"), max_length=50)

    class Meta:
        db_table = "queue"
        verbose_name = _("Fila")
        verbose_name_plural = _("Filas")

    def __str__(self):
        return self.title


@python_2_unicode_compatible
class Sla(models.Model):

    queue = models.ForeignKey(Queue, related_name="sla", verbose_name=_("Fila"))
    reference = models.CharField(
        _("Referência"),
        max_length=10,
        help_text=_("Informe a referência (se houver) do contrato para este SLA."),
        blank=True
    )
    service = models.CharField(_("Serviço"), max_length=50)
    description = models.TextField(_("Descrição"), blank=True)
    days_budget = models.PositiveSmallIntegerField(
        _("Estimativa"),
        help_text=_("Informe o prazo máximo em dias para elaboração de estimativa."),
        default=0
    )
    days_start_attendance = models.PositiveSmallIntegerField(
        _("Início do atendimento"),
        help_text=_("Informe o prazo máximo em dias para início do atendimento."),
        default=0
    )
    days_delivery = models.PositiveSmallIntegerField(
        _("Execução do serviço"),
        help_text=_("Informe o prazo máximo em dias para execução do serviço."),
        default=2
    )
    value = models.PositiveIntegerField(
        _("Valor"),
        help_text=_("Informe o valor unitário deste SLA."),
        blank=True,
        null=True
    )

    class Meta:
        db_table = "sla"
        verbose_name = _("SLA")
        verbose_name_plural = _("SLAs")

    def __str__(self):
        return self.service


class StatusChoice(Choice):
    OPEN = u"open", _("Aberto")
    WORKING = u"working", _("Em andamento")
    CLOSED = u"closed", _("Fechado")
    W_USER = u"waiting_user", _("Aguardando usuário")
    W_CLIENT = u"waiting_client", _("Aguardando cliente")
    W_RESOURCES = u"waiting_resources", _("Aguardando recursos")
    W_SUPPLIER = u"waiting_supplier", _("Aguardando fornecedor")


@python_2_unicode_compatible
class Ticket(models.Model):

    identifier = models.CharField(
        _("Identificador"),
        help_text=_("Informe o ID ou outro identificador do ticket."),
        max_length=10
    )
    title = models.CharField(
        _("Título"),
        max_length=150
    )
    start_date = models.DateField(
        _("Data de abertura"),
    )
    end_date = models.DateField(
        _("Data de encerramento"),
        blank=True,
        null=True
    )
    sla = models.ForeignKey(Sla, related_name="tickets", verbose_name=_("SLA"))
    state = FSMField(_("Status"), choices=StatusChoice, default=StatusChoice.OPEN)

    class Meta:
        db_table = "ticket"
        verbose_name = _("Ticket")
        verbose_name_plural = _("Tickets")
        ordering = ["-start_date", "-end_date"]

    def __str__(self):
        return self.title

    def _get_interruption_days(self):
        count = 0
        interruptions = self.history.filter(interruption=True)
        for interrupt in interruptions:
            if interrupt.end_date:
                calc = interrupt.end_date - interrupt.start_date
                if calc.days >= 1:
                    work_days = networkdays(interrupt.start_date, interrupt.end_date)
                    count += work_days - 1
        return count

    def latest_status(self):
        status = Status.objects.select_related("ticket").filter(ticket=self).first()
        return status

    def due_date(self):
        max = self.sla.days_budget + self.sla.days_start_attendance + self.sla.days_delivery
        break_days = self._get_interruption_days()
        max += break_days
        due_date = workday(self.start_date, max)
        return due_date

    @transition(field=state, source="closed", target="open")
    def open(self):
        pass

    @transition(field=state, source="*", target="working")
    def working(self):
        pass

    @transition(field=state, source="*", target="closed")
    def close(self):
        pass

    @transition(field=state, source="*", target="waiting_user")
    def waiting_user(self):
        pass

    @transition(field=state, source="*", target="waiting_client")
    def waiting_client(self):
        pass

    @transition(field=state, source="*", target="waiting_resources")
    def waiting_resoures(self):
        pass

    @transition(field=state, source="*", target="waiting_supplier")
    def waiting_supplier(self):
        pass


@python_2_unicode_compatible
class Status(models.Model):

    ticket = models.ForeignKey(Ticket, related_name="history")
    state = models.CharField(_("Status"), max_length=20, default="open", choices=StatusChoice)
    note = models.TextField(_("Observações"), blank=True)
    start_date = models.DateField(_("Data"))
    end_date = models.DateField(_("Finalizado"), blank=True, null=True)
    modified = models.DateTimeField(_("Modificado"), auto_now=True)
    interruption = models.BooleanField(_("Interrupção"), default=False)

    class Meta:
        db_table = "status"
        verbose_name = _("Status")
        verbose_name_plural = _("Status")
        ordering = ["-start_date", "-modified"]

    def __str__(self):
        return self.get_state_display()

apps/core/forms.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Ticket, Sla, Status


class TicketForm(forms.ModelForm):

    sla = forms.ModelChoiceField(
        queryset=Sla.objects.all(),
        empty_label=_("-- Escolha um SLA --"),
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'placeholder': _("SLA"),
            },
        ),
    )

    class Meta:
        model = Ticket
        fields = ("identifier", "title", "start_date", "sla")
        exclude = ("end_date", "state")
        widgets = {
            'identifier': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _("10203040")
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _("Título"),
                }
            ),
            'start_date': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _("DD/MM/AAAA")
                }
            ),
            'end_date': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': _("DD/MM/AAAA")
                }
            ),
        }

    def save(self, commit=True):
        obj = super(TicketForm, self).save(commit=False)
        if commit:
            if not obj.pk:
                obj.save()
                status = Status(
                    state="open",
                    ticket=obj,
                    start_date=obj.start_date
                )
                status.save()
                return obj
            obj.save()
        return obj


class StatusForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = ("ticket", "state", "note", "start_date")
        exclude = ("end_date", "interruption", "modified")
        widgets = {
            'ticket': forms.HiddenInput(),
            'state': forms.HiddenInput(),
            'note': forms.Textarea(attrs={'class': 'form-control'}),
            'start_date': forms.TextInput(attrs={'class': 'form-control'}),
            'end_date': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        obj = super(StatusForm, self).save(commit=False)
        if commit:
            interruptions = ["waiting_user", "waiting_supplier",
                             "waiting_client", "waiting_resources"]
            if obj.state in interruptions:
                obj.interruption = True
            obj.save()
        return obj

apps/core/templates/core/index.html
{% extends 'base.html' %}

{% block title %}Página inicial{% endblock %}

{% block content %}
<div class="row">

    <div class="col-md-6 col-xs-12">

        <div class="widget stacked">

            <div class="widget-header">
                <i class="icon-star"></i>
                <h3>Tickets abertos</h3>
            </div> <!-- /widget-header -->

            <div class="widget-content">

                <div class="stats">

                    <div class="stat">
                        <span class="stat-value">5</span>
                        Projetos
                    </div> <!-- /stat -->

                    <div class="stat">
                        <span class="stat-value">7</span>
                        Desenvolvimento
                    </div> <!-- /stat -->

                    <div class="stat">
                        <span class="stat-value">4</span>
                        Sustentação
                    </div> <!-- /stat -->

                </div> <!-- /stats -->

            </div> <!-- /widget-content -->

        </div> <!-- /widget -->

    </div> <!-- /span6 -->


    <div class="col-md-6 col-xs-12">

        <div class="widget stacked">

            <div class="widget-header">
                <i class="icon-bookmark"></i>
                <h3>Acesso rápido</h3>
            </div> <!-- /widget-header -->

            <div class="widget-content">

                <div class="shortcuts">

                    <a href="{% url 'tickets:add' %}" class="shortcut">
                        <i class="shortcut-icon icon-plus"></i>
                        <span class="shortcut-label">Novo ticket</span>
                    </a>

                    <a href="javascript:;" class="shortcut">
                        <i class="shortcut-icon icon-cogs"></i>
                        <span class="shortcut-label">Sustentação</span>
                    </a>

                    <a href="javascript:;" class="shortcut">
                        <i class="shortcut-icon icon-coffee"></i>
                        <span class="shortcut-label">Desenvolvimento</span>
                    </a>

                    <a href="javascript:;" class="shortcut">
                        <i class="shortcut-icon icon-laptop"></i>
                        <span class="shortcut-label">Projetos</span>
                    </a>

                </div> <!-- /shortcuts -->

            </div> <!-- /widget-content -->

        </div> <!-- /widget -->

    </div> <!-- /span6 -->

</div> <!-- /row -->
{% endblock %}

apps/core/templates/core/status_form.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Atualizar status{% endblock %}


{% block breadcrumbs %}
    <li><a href="{% url 'tickets:list' %}">Tickets</a></li>
    <li><a href="{% url 'tickets:view' ticket.pk %}">{{ ticket }}</a></li>
    <li class="active">Novo status</li>
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-md-12">

            <div class="widget stacked">

                <div class="widget-header">
                    <i class="icon-ticket"></i>
                    <h3>Novo status: {{ status }}</h3>
                </div>

                <div class="widget-content">
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}

                        <div class="col-md-12">
                            <h4><strong>#{{ ticket.identifier }}</strong>: {{ ticket }}</h4>
                        </div>

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ form.non_field_errors.as_text }}
                            </div>
                        {% endif %}

                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}

                        <!-- note field -->
                        <div class="form-group {% if form.note.errors %}has-error{% endif %}">
                            {% if form.note.errors %}
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="text-danger" role="alert">
                                    {{ form.note.errors.as_text }}
                                </div>
                            </div>
                            {% endif %}
                            <label class="col-sm-2 control-label" for="{{ form.note.id_for_label }}">{{ form.note.label }}</label>
                            <div class="col-sm-6">
                                {{ form.note }}
                                <span class="help-block m-b-none">{{ form.note.help_text }}</span>
                            </div>
                        </div>
                        <!-- // end of: note field -->
                        <!-- start_date field -->
                        <div class="form-group {% if form.start_date.errors %}has-error{% endif %}">
                            {% if form.start_date.errors %}
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="text-danger" role="alert">
                                    {{ form.start_date.errors.as_text }}
                                </div>
                            </div>
                            {% endif %}
                            <label class="col-sm-2 control-label" for="{{ form.start_date.id_for_label }}">{{ form.start_date.label }}</label>
                            <div class="col-sm-2">
                                {{ form.start_date }}
                                <span class="help-block m-b-none">{{ form.start_date.help_text }}</span>
                                <a href="#" id="today_shortcut">Hoje</a>
                            </div>
                        </div>
                        <!-- // end of: start_date field -->
                         <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-default block full-width m-b">Salvar</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>

        </div>

    </div>


{% endblock %}

{% block js %}

    <script type="text/javascript">
        $(document).ready(function() {
            $("#id_start_date").datepicker().mask("99/99/9999");
            $("#today_shortcut").click(function(e) {
                e.preventDefault();
                var time = new Date();
                $('#id_start_date').val(time.toLocaleFormat("%d/%m/%Y"));
            });
        });
    </script>

{% endblock %}

apps/core/templates/core/ticket_detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load history_labels %}

{% block title %}Tickets cadastrados{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/timeline.css' %}"/>
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tickets:list' %}">Tickets</a></li>
    <li class="active">{{ object }}</li>
{% endblock %}

{% block content %}

<div class="row">

    <div class="col-md-12">

        <div class="widget stacked">

            <div class="widget-header">
                <i class="icon-ticket"></i>
                <h3>{{ object }}</h3>
            </div>

            <div class="widget-content">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</td>
                            <th>Título</td>
                            <th>Aberto</td>
                            <th>Previsto</th>
                            <th>Fechado</td>
                            <th>SLA</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{{ object.identifier }}</td>
                            <td>{{ object.title }}</td>
                            <td>{{ object.start_date|date:"d/m/Y" }}</td>
                            <td>{{ object.due_date|date:"d/m/Y" }}</td>
                            <td>{{ object.end_date|date:"d/m/Y" }}</td>
                            <td>{{ object.sla }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

        </div>

    </div>

</div>

<div class="row">

    <div class="col-md-12">

        <div class="widget stacked">

            <div class="widget-header">
                <i class="icon-ticket"></i>
                <h3>Histórico</h3>
            </div>

            <div class="widget-content">
                <ul class="timeline">
                    {% for history in object.history.all %}
                    <li {% if forloop.counter|divisibleby:2 %}class="timeline-inverted"{% endif %}>
                        <div class="timeline-badge {{ history.state|badge_color }}">
                          <i class="icon {{ history.state|icon_label }}"></i>
                        </div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                              <h4 class="timeline-title">{{ history.get_state_display }}</h4>
                              <p>
                                <small class="text-muted">
                                    <i class="icon icon-calendar"></i>
                                    {{ history.start_date|date:"d/m/Y" }} - {{ history.end_date|date:"d/m/Y" }}
                                </small>
                              </p>
                            </div>
                            <div class="timeline-body">
                              <p>{{ history.note }}</p>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>

        </div>

    </div>

</div>

{% endblock %}

apps/core/templates/core/ticket_form.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}Cadastrar ticket{% endblock %}

{% block stylesheets %}

    <link href="{% static 'js/plugins/chosen/chosen.min.css' %}" rel="stylesheet">

{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tickets:list' %}">Tickets</a></li>
    <li class="active">Cadastrar ticket</li>
{% endblock %}

{% block content %}

    <div class="row">

        <div class="col-md-12">

            <div class="widget stacked">

                <div class="widget-header">
                    <i class="icon-ticket"></i>
                    <h3>Cadastrar novo ticket</h3>
                </div>

                <div class="widget-content">
                    <form method="post" class="form-horizontal">
                        {% csrf_token %}

                        <!-- identifier field -->
                        <div class="form-group {% if form.identifier.errors %}has-error{% endif %}">
                            {% if form.identifier.errors %}
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="text-danger" role="alert">
                                    {{ form.identifier.errors.as_text }}
                                </div>
                            </div>
                            {% endif %}
                            <label class="col-sm-2 control-label" for="{{ form.identifier.id_for_label }}">{{ form.identifier.label }}</label>
                            <div class="col-sm-2">
                                <div class="input-group">
                                    <span class="input-group-addon" id="basic-addon1">#</span>
                                    {{ form.identifier }}
                                </div>
                                <span class="help-block m-b-none">{{ form.identifier.help_text }}</span>
                            </div>
                        </div>
                        <!-- // end of: identifier field -->
                        <!-- title field -->
                        <div class="form-group {% if form.title.errors %}has-error{% endif %}">
                            {% if form.title.errors %}
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="text-danger" role="alert">
                                    {{ form.title.errors.as_text }}
                                </div>
                            </div>
                            {% endif %}
                            <label class="col-sm-2 control-label" for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
                            <div class="col-sm-6">
                                {{ form.title }}
                                <span class="help-block m-b-none">{{ form.title.help_text }}</span>
                            </div>
                        </div>
                        <!-- // end of: title field -->
                        <!-- start_date field -->
                        <div class="form-group {% if form.start_date.errors %}has-error{% endif %}">
                            {% if form.start_date.errors %}
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="text-danger" role="alert">
                                    {{ form.start_date.errors.as_text }}
                                </div>
                            </div>
                            {% endif %}
                            <label class="col-sm-2 control-label" for="{{ form.start_date.id_for_label }}">{{ form.start_date.label }}</label>
                            <div class="col-sm-2">
                                {{ form.start_date }}
                                <span class="help-block m-b-none">{{ form.start_date.help_text }}</span>
                                <a href="#" id="today_shortcut">Hoje</a>
                            </div>
                        </div>
                        <!-- // end of: start_date field -->
                        <!-- sla field -->
                        <div class="form-group {% if form.sla.errors %}has-error{% endif %}">
                            {% if form.sla.errors %}
                            <div class="col-sm-10 col-sm-offset-2">
                                <div class="text-danger" role="alert">
                                    {{ form.sla.errors.as_text }}
                                </div>
                            </div>
                            {% endif %}
                            <label class="col-sm-2 control-label" for="{{ form.sla.id_for_label }}">{{ form.sla.label }}</label>
                            <div class="col-sm-3">
                                {{ form.sla }}
                                <span class="help-block m-b-none">{{ form.sla.help_text }}</span>
                            </div>
                        </div>
                        <!-- // end of: sla field -->
                         <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-default block full-width m-b">Salvar</button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>

        </div>

    </div>


{% endblock %}

{% block js %}

    <script type="text/javascript" src="{% static 'js/plugins/chosen/chosen.jquery.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#id_start_date").datepicker().mask("99/99/9999");
            $("#today_shortcut").click(function(e) {
                e.preventDefault();
                var time = new Date();
                $('#id_start_date').val(time.toLocaleFormat("%d/%m/%Y"));
            });
            $("#id_sla").chosen({
                inherit_select_classes: true,
                no_results_text: "Nenhum resultado encontrado"
            });
        });
    </script>

{% endblock %}